language: node_js                                                                                                                                                                                           
node_js:
          - "6"

before_script: cd BuildingJavaScriptDevelopmentEnvironment/exercises/One/
